import 'package:interviews/models/myinterviews.dart';

final interviewList = <MyInterviews>[
  MyInterviews(
      interviewid: 1,
      name: 'jwan',
      companyName: "google",
      vacant: 'flutter',
      employee1: 'Ahmad',
      employee2: 'mohamad',
      employee3: 'Fawzi',
      model: 'A',
      Date: '22/2/2021',
      result: 70),
  MyInterviews(
      interviewid: 1,
      name: 'jwan',
      companyName: "google",
      vacant: 'flutter',
      employee1: 'Ahmad',
      employee2: 'mohamad',
      employee3: 'Fawzi',
      model: 'A',
      Date: '22/2/2021',
      result: 70),
  MyInterviews(
      interviewid: 1,
      name: 'jwan',
      companyName: "google",
      vacant: 'flutter',
      employee1: 'Ahmad',
      employee2: 'mohamad',
      employee3: 'Fawzi',
      model: 'A',
      Date: '22/2/2021',
      result: 70),
  MyInterviews(
      interviewid: 1,
      name: 'jwan',
      companyName: "google",
      vacant: 'flutter',
      employee1: 'Ahmad',
      employee2: 'mohamad',
      employee3: 'Fawzi',
      model: 'A',
      Date: '22/2/2021',
      result: 70),
  MyInterviews(
      interviewid: 1,
      name: 'jwan',
      companyName: "google",
      vacant: 'flutter',
      employee1: 'Ahmad',
      employee2: 'mohamad',
      employee3: 'Fawzi',
      model: 'A',
      Date: '22/2/2021',
      result: 70),
  MyInterviews(
      interviewid: 1,
      name: 'jwan',
      companyName: "google",
      vacant: 'flutter',
      employee1: 'Ahmad',
      employee2: 'mohamad',
      employee3: 'Fawzi',
      model: 'A',
      Date: '22/2/2021',
      result: 70),
  MyInterviews(
      interviewid: 1,
      name: 'jwan',
      companyName: "google",
      vacant: 'flutter',
      employee1: 'Ahmad',
      employee2: 'mohamad',
      employee3: 'Fawzi',
      model: 'A',
      Date: '22/2/2021',
      result: 70),
  MyInterviews(
      interviewid: 1,
      name: 'jwan',
      companyName: "google",
      vacant: 'flutter',
      employee1: 'Ahmad',
      employee2: 'mohamad',
      employee3: 'Fawzi',
      model: 'A',
      Date: '22/2/2021',
      result: 70),
  MyInterviews(
      interviewid: 1,
      name: 'jwan',
      companyName: "google",
      vacant: 'flutter',
      employee1: 'Ahmad',
      employee2: 'mohamad',
      employee3: 'Fawzi',
      model: 'A',
      Date: '22/2/2021',
      result: 70),
  MyInterviews(
      interviewid: 1,
      name: 'messi',
      companyName: "google",
      vacant: 'flutter',
      employee1: 'Ahmad',
      employee2: 'mohamad',
      employee3: 'Fawzi',
      model: 'A',
      Date: '22/2/2021',
      result: 70),
];
